name: Build and deploy Laravel app to Azure Web App - video-tiktok-main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, pdo_mysql, bcmath, openssl

      - name: Create .env file for build
        run: |

          echo "APP_ENV=production" >> .env
          echo "APP_DEBUG=true" >> .env
          echo "APP_KEY=base64:placeholderkey1234567890" >> .env
          echo "APP_URL=https://video-tiktok-main-erehckdxh9cgh2gg.canadacentral-01.azurewebsites.net" >> .env

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Generate Laravel APP_KEY and cache config
        run: |
          php artisan key:generate
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies and build assets
        run: |
          npm install
          npm run build

      - name: Clean up temporary .env (optional)
        run: rm .env

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: laravel-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: laravel-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9644BEBEECA8414DB5C685C92F12571F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_64CB071F91534970B3F993F2D1457DA9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D9FC9021F5B044A0AD58BFF1075B4C72 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'video-tiktok-main'
          slot-name: 'Production'
          package: .



